# Site settings
title: She codes
header-img: img/home-bg.png
email: juliajen.prog@gmail.com
copyright_name: JulJen
description: > # this means to ignore newlines until "baseurl:"
  my dev journey 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JulJen
learn_profile: JulJen
email_username: juliajen.prog@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
